### ISSUE TITLE
Question 8: same answer multiple times. Only one correct

### ISSUE THREAD

**Issue by campbellbartlett** [OTR500miles2go/hf_quiz_machine#2]
Loved the quiz, the site looks great and is a breeze to use.

When I did my quiz I got the same choices for question 8 3 times, but only one of them was correct. Am I missing something or is this a mistake?

<img width="647" alt="Screen Shot 2019-05-28 at 8 30 42 am" src="https://user-images.githubusercontent.com/38512252/58441182-2d93a500-8123-11e9-9059-8ecf68303427.png">
<img width="647" alt="Screen Shot 2019-05-28 at 8 30 37 am" src="https://user-images.githubusercontent.com/38512252/58441183-2ec4d200-8123-11e9-9dc4-a7c2287594fd.png">

**Comment by OTR500miles2go** [comment]
It's an error.  I'll track it down asap. Thanks!

**Comment by OTR500miles2go** [comment]
I reset the pg DATABASE to fix the issue.

**Comment by campbellbartlett** [comment]
Looks good to me!
